type: cluster

replicaCount: 3

image:
  repository: nacos/nacos-server
  pullPolicy: IfNotPresent
  tag: "1.4.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

database:
  type: mysql
  mysqlHost: "mysql"
  mysqlPort: 3306
  mysqlUser: root
  mysqlDb: nacos
  mysqlPassword: "123456"

volume:
  enabled: false

env:
- name: JVM_XMX
  value: 2g

config: |
  management.endpoints.web.exposure.include=*

resources:
  limits:
    cpu: 1
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}
