type: cluster

replicaCount: 3

image:
  repository: nacos/nacos-server
  pullPolicy: IfNotPresent
  tag: "1.4.1"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volume:
  enabled: true
  storageSize: 1Gi
  storageClassName: default

database:
  type: embedded

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

config: |
  management.endpoints.web.exposure.include=*

nodeSelector: {}

tolerations: []

affinity: {}
