# permissions for end users to view nacos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nacos-viewer-role
rules:
- apiGroups:
  - nacos.io
  resources:
  - nacos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nacos.io
  resources:
  - nacos/status
  verbs:
  - get
