apiVersion: harmonycloud.cn/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  # standalone/cluster
  type: cluster
  image: nacos/nacos-server:1.4.1
  replicas: 3
  enableEmbedded: true
#  config: |
#    nacos.naming.data.warmup=false
