apiVersion: harmonycloud.cn/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  # standalone/cluster
  type: standalone
  image: 10.1.11.100/middleware/nacose:1.4.0
  replicas: 1
  # 开启本地数据库
  enableEmbedded: true

