apiVersion: harmonycloud.cn/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  # standalone/cluster
  type: standalone
  image: nacos/nacos-server:1.4.1
  replicas: 1
  database:
    type: embedded
  volume:
    enabled: true
    requests:
      storage: 1Gi
    storageClass: middleware-lvm



