apiVersion: harmonycloud.cn/v1alpha1
kind: Nacos
metadata:
  name: {{ include "nacos.fullname" . }}
spec:
  # standalone/cluster
  type: {{ .Values.type}}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  enableEmbedded: {{ .Values.enableEmbedded }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  replicas: {{ .Values.replicaCount}}
  {{- with .Values.nodeSelector }}
  nodeSelector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.config }}
  config: |
    nacos.naming.distro.taskDispatchThreadCount=10
	  nacos.naming.distro.taskDispatchPeriod=200
	  nacos.naming.distro.batchSyncKeyCount=1000
	  nacos.naming.distro.initDataRatio=0.9
	  nacos.naming.distro.syncRetryDelay=5000
	  nacos.naming.data.warmup=true
{{ .Values.config | indent 4 }}
  {{- end }}
{{-  if .Values.storage.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.storageClassName}}
      resources:
        requests:
          storage: {{ .Values.storage.storageSize}}
{{-  end }}
